my_string=input("Введите ваше имя: ")
quantity_in_string=len(my_string)
print(quantity_in_string)
print(my_string.upper())
print(my_string.lower())
my_string_new = my_string.replace(' ','')
print(my_string_new)
print(my_string[0])
print(my_string[-1])